import { definePreset } from '@primevue/themes'
import Aura from '@primevue/themes/aura'
import type { PrimeVueConfiguration } from 'primevue'

const Windows11Preset = definePreset(Aura, {
  semantic: {
    primary: {
      50: '#e5f1fb',
      100: '#b3d7f2',
      200: '#80bde9',
      300: '#4da3e0',
      400: '#2690d9',
      500: '#0078D4',
      600: '#006cbe',
      700: '#005A9E',
      800: '#004880',
      900: '#003662',
      950: '#002444',
    },
    colorScheme: {
      light: {
        primary: {
          color: '#0078D4',
          inverseColor: '#ffffff',
          hoverColor: '#005A9E',
          activeColor: '#004880',
        },
        highlight: {
          background: '#0078D4',
          focusBackground: '#005A9E',
          color: '#ffffff',
          focusColor: '#ffffff',
        },
      },
    },
  },
})

export const primevueConfig: PrimeVueConfiguration = {
  theme: {
    preset: Windows11Preset,
    options: {
      darkModeSelector: '.app-dark',
    },
  },
  locale: {
    accept: 'Sim',
    reject: 'Nao',
    choose: 'Escolher',
    upload: 'Enviar',
    cancel: 'Cancelar',
    dayNames: ['Domingo', 'Segunda', 'Terca', 'Quarta', 'Quinta', 'Sexta', 'Sabado'],
    dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
    dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
    monthNames: ['Janeiro', 'Fevereiro', 'Marco', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
    today: 'Hoje',
    weekHeader: 'Sem',
    firstDayOfWeek: 0,
    dateFormat: 'dd/mm/yy',
    weak: 'Fraco',
    medium: 'Medio',
    strong: 'Forte',
    passwordPrompt: 'Digite uma senha',
    emptyFilterMessage: 'Nenhum resultado encontrado',
    emptyMessage: 'Nenhuma opcao disponivel',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    aria: {
      trueLabel: 'Verdadeiro',
      falseLabel: 'Falso',
      nullLabel: 'Nao selecionado',
      star: '1 estrela',
      stars: '{star} estrelas',
      selectAll: 'Todos selecionados',
      unselectAll: 'Todos desmarcados',
      close: 'Fechar',
      previous: 'Anterior',
      next: 'Proximo',
      navigation: 'Navegacao',
      scrollTop: 'Rolar para cima',
      moveTop: 'Mover para cima',
      moveUp: 'Mover acima',
      moveDown: 'Mover abaixo',
      moveBottom: 'Mover para baixo',
      moveToTarget: 'Mover para destino',
      moveToSource: 'Mover para origem',
      moveAllToTarget: 'Mover tudo para destino',
      moveAllToSource: 'Mover tudo para origem',
      pageLabel: 'Pagina {page}',
      firstPageLabel: 'Primeira pagina',
      lastPageLabel: 'Ultima pagina',
      nextPageLabel: 'Proxima pagina',
      prevPageLabel: 'Pagina anterior',
      rowsPerPageLabel: 'Linhas por pagina',
      jumpToPageDropdownLabel: 'Ir para pagina',
      jumpToPageInputLabel: 'Ir para pagina',
      selectRow: 'Linha selecionada',
      unselectRow: 'Linha desmarcada',
      expandRow: 'Linha expandida',
      collapseRow: 'Linha recolhida',
      showFilterMenu: 'Mostrar filtro',
      hideFilterMenu: 'Esconder filtro',
      filterOperator: 'Operador de filtro',
      filterConstraint: 'Restricao de filtro',
      editRow: 'Editar linha',
      saveEdit: 'Salvar edicao',
      cancelEdit: 'Cancelar edicao',
      listView: 'Visao em lista',
      gridView: 'Visao em grade',
      slide: 'Slide',
      slideNumber: '{slideNumber}',
      zoomImage: 'Ampliar imagem',
      zoomIn: 'Aumentar zoom',
      zoomOut: 'Diminuir zoom',
      rotateRight: 'Girar para direita',
      rotateLeft: 'Girar para esquerda',
    },
  },
}
